services:
  client:
    container_name: pp.client
    ports:
      - "5173:5173"
    build:
      context: ./site
      dockerfile: ./Dockerfile
    volumes:
      - ./site:/site
    depends_on:
      - api
      
  api:
    container_name: pp.server
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    build:
      context: ./src
      dockerfile: ./Dockerfile
    volumes:
      - ./:/source 
    networks:
      - app
    depends_on:
      - db

  db:
    container_name: pp.db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_db
      POSTGRES_PASSWORD: app_db_password_1234
    networks:
      - app
    volumes:
      - postgres_data:/var/lib/postgresql

networks:
  app:
    driver: bridge

volumes:
  postgres_data: